import React, { useContext, useEffect, useState } from "react"
import { TaskContext } from "./TaskProvider"
import ".Task.css"
import { useParams } from "react-router-dom"
import { useHistory } from "react-router-dom"